### ISSUE TITLE
on-demand price is 0.0000

### ISSUE THREAD

**Issue by melkosoft** [argoproj/k8s-minion-manager#15]
I installed kubernetes 1.10 and started minion-manager using yaml file from deploy folder. I tagged ASG with "KubernetesCluster"="my-cluster-name" and "minion-manager"="on-spot". After some time log shows 
>>>>INFO aws.minion-manager.bid-advisor MainThread: Using spot_instance price 0.013900, on-demand price 0.000000 for instance type: t2.medium, zones: ['us-east-1a', 'us-east-1b']. Why is that? There was no errors in the log.

**Comment by shrinandj** [comment]
Can you share more logs? What instance type was being used?

**Comment by melkosoft** [comment]
I have no log - it was long time ago when I tried it. I remember that I used xlarge instance

**Comment by shrinandj** [comment]
I'll try it out and update this issue.

**Comment by shrinandj** [comment]
Used minion-manager with instance types `c5.xlarge` and it worked just fine:

```
2019-02-16T01:46:45 INFO aws.minion-manager.bid-advisor Thread-3: Using spot_instance price 0.070100, on-demand price 0.170000 for instance type: c5.xlarge, zones: ['us-west-2a', 'us-west-2b', 'us-west-2c']
```
