### ISSUE TITLE
Certain Instance types have on-demand price is 0.0000

### ISSUE THREAD

**Issue by jpresky** [argoproj/k8s-minion-manager#24]
I saw that these two issues below are similar to mine and were closed. 
https://github.com/argoproj/k8s-minion-manager/issues/15
https://github.com/argoproj/k8s-minion-manager/issues/10

The bug still seems to be in the code and also affects m5a.2xlarge instances

I have a fix. What is the best way to share it? I am getting a 403 when I try to push up my branch.

Thanks!

**Comment by shrinandj** [comment]
Hey @jpresky, thanks for proposing a fix. Best option to share would be to fork the repo, push to a branch in your own fork and create a PR against this repo. That should not have permissions issues. Let me know if you run into that.

**Comment by jpresky** [comment]
I realize now that I experienced this issue because I was using an old image referenced in mm.yaml.

https://github.com/argoproj/k8s-minion-manager/pull/25 I updated the mm.yaml to latest and some documentation here.
