### ISSUE TITLE
On-demand instances get terminated all together

### ISSUE THREAD

**Issue by shrinandj** [argoproj/k8s-minion-manager#9]
Currently, all on-demand instances in an ASG get terminated together when the minion-manager decides to use spot instances. This has it's pros and cons. The benefit of this is that new instances all come-up in parallel shortening the time for which on-demand instances run (and therefore keeps costs low). However, this can lead to service disruption.

Ideally, it should be possible to chose what termination strategy is to be used.

Maybe, add another tag?
`k8s-minion-manager/num-simultaneous-terminations: 1` will terminate one instance at a time.
`k8s-minion-manager/num-simultaneous-terminations: all` will terminate all instances together.

**Comment by backjo** [comment]
When instances are scheduled for termination but not terminated, we might consider tainting them as well so we don't schedule new pods on them.

**Comment by shrinandj** [comment]
Commit f6517bb added functionality to terminate one instance at a time.

Cordon and draining of nodes is being tracked by https://github.com/argoproj/k8s-minion-manager/issues/19.

Closing this one.
